# Generated by Django 4.2.16 on 2025-01-27 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_delete_snippet'),
    ]

    operations = [
        migrations.CreateModel(
            name='legal_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pan_number', models.IntegerField()),
                ('citizenship_number', models.IntegerField()),
            ],
        ),
    ]
